name: tf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - pip:
    - tensorflow==2.10.0
    - "numpy<2.0"
    - opencv-python
    - sounddevice
    - soundfile
    - mediapipe
    - Pillow
    - tensorflow_hub
    - tensorflow_io
    - tqdm